### ISSUE TITLE
Style Header underlines and add gray border

### ISSUE THREAD

**Issue by srazh** [gruepr/gruepr-webapp#17]
The purpose of this ticket is to style the header with blue underlines when it is on that page

Refer to the figma design 
https://www.figma.com/file/eaRNSDk0JCclyQqiMlHc5m/Hi-Fis?node-id=0%3A1&t=RixDEzl2TGGGXqtT-0

<img width="579" alt="Screen Shot 2022-11-20 at 11 28 04 AM" src="https://user-images.githubusercontent.com/63278213/202913686-d4423cef-274e-425b-8fa6-b8e8e89fe73e.png">

**Comment by caocynthia** [comment]
The header design was also updated with a gray line at the bottom of the header. The color is neutral-200
