### ISSUE TITLE
Fix alignment issue for Youtube embeds

### ISSUE THREAD

**Issue by srazh** [gruepr/gruepr-webapp#18]
The purpose of this ticket is the fix the styling for the last two Youtube Embds. Right now the last two are vertical instead of horizontal

<img width="727" alt="Screen Shot 2022-11-20 at 11 32 44 AM" src="https://user-images.githubusercontent.com/63278213/202913926-025d68d2-ce06-4799-a56d-97e0401767a8.png">

**Comment by minafletcher** [comment]
happening because of an extra wrapping div tag!
